name: "反馈Bug"
description: 在这里反馈你遇到的Bug
title: "📄[Bug Report] 请输入标题"
labels: ["bug"]
body:
    - type: checkboxes
      id: check-list
      attributes:
          label: "检查项"
          description: "请逐个检查下列项目，并勾选确认。"
          options:
              - label: "我确认有此Bug并知道如何复现"
                required: true
              - label: "我确认有此Bug但不知如何复现"
                required: true
    - type: textarea
      id: description
      attributes:
          label: "描述问题"
          description: 请简单描述您遇到的问题
          placeholder: 问题描述……
          render: bash
      validations:
          required: true
    - type: textarea
      id: reprod
      attributes:
          label: "如何复现你的遇到的问题？"
          description: 请详细描述如何复现你遇到的问题
          value: |
              1. 
              2. 
              3. 
              4. 
              5. 问题复现
          render: bash
      validations:
          required: true
    - type: textarea
      id: screenshots
      attributes:
          label: 截图
          description: 如果有相关截图的话，请上传截图。
          placeholder: 请把截图粘贴到这里
    - type: dropdown
      id: dropdown
