name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build exe with PyInstaller
      run: |
        pyinstaller -F GuessTheNumber.py  # 使用 -F 选项生成单个文件
    - name: Upload exe as artifact
      uses: actions/upload-artifact@v4
      with:
        name: GuessTheNumber
        path: dist/GuessTheNumber  # 直接上传生成的文件
